### PR TITLE
Shortest Path Query fix #368

### LINKED ISSUE #368: Shortest Path query fails if id of start or end node is 0

### PR DESCRIPTION
**Pull request by joluj**

### CODE REVIEW

File: backend/src/shortest-path/shortest-path.controller.ts [hunk 1]
```diff
@@ -36,11 +36,11 @@ export class ShortestPathController {
       throw new BadRequestException();
     }
 
-    if (!query.startNode) {
+    if (query.startNode == null) {
```
Comment (CatoLeanTruetschel) [inline backend/src/shortest-path/shortest-path.controller.ts:39]: Always use strict equality comparison. This will fail in the CI tests. 
Better use either   
`!query.startNode && query.startNode !== 0)`   
or   
`query.startNode === null || query.startNode === undefined`

File: backend/src/shortest-path/shortest-path.controller.ts [hunk 2]
```diff
@@ -36,11 +36,11 @@ export class ShortestPathController {
...
       throw new BadRequestException();
     }
 
-    if (!query.endNode) {
+    if (query.endNode == null) {
```
Comment (CatoLeanTruetschel) [inline backend/src/shortest-path/shortest-path.controller.ts:43]: Always use strict equality comparison. This will fail in the CI tests.
Better use either
`!query.endNode && query.endNode !== 0)`
or
`query.endNode === null || query.endNode === undefined`

**Review by CatoLeanTruetschel — CHANGES_REQUESTED** [review]

**Review by CatoLeanTruetschel — APPROVED** [review]
LGTM
