### PR TITLE
Test fix

### LINKED ISSUE #301: Fix failing CI
CI is failing since the backend tries to connect to the database too soon (before it's completely running).

### PR DESCRIPTION
**Pull request by joluj**
Fixes failing CI-
Closes #301.

### CODE REVIEW

File: backend/wait-on-db.js [hunk 1]
```diff
@@ -0,0 +1,55 @@
...
+const config = {
+  scheme: process.env.NEO4J_SCHEME,
+  host: process.env.NEO4J_HOST,
+  port: process.env.NEO4J_PORT,
+  username: process.env.NEO4J_USERNAME,
+  password: process.env.NEO4J_PASSWORD,
+};
+
+// eslint-disable-next-line no-console
+console.log(config);
```
Comment (derwehr) [inline backend/wait-on-db.js:23]: remove or add 1-2 words to the output saying what it is you're logging here

**Review by derwehr — APPROVED** [review]
